services:
  db:
    image: postgres:17
    container_name: amigo-tvde-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: amigo-tvde-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5435:5432"

volumes:
  pgdata: